services:
  - type: web
    name: down-subtitle
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
    startCommand: |
      heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:kHAd8H8/BnJlJcaC/EAbPTfMB2vfKskPg3N/1A/jOqg=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: down-subtitle
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rajveer04
